# Generated by Django 3.2.9 on 2021-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('timeStamp', models.IntegerField()),
                ('content', models.TextField()),
                ('splitWords', models.TextField()),
            ],
            options={
                'db_table': 'top_news',
            },
        ),
    ]
