# Generated by Django 3.2.9 on 2021-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_topnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('timeStamp', models.CharField(max_length=255)),
                ('words', models.TextField()),
            ],
            options={
                'db_table': 'frequency',
            },
        ),
    ]
