# Generated by Django 3.2.9 on 2021-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='repeat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
